# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x07monitor\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cPongResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x0eMetricsRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"\x1f\n\x0fMetricsResponse\x12\x0c\n\x04load\x18\x01 \x01(\x05\"&\n\x0fRegisterRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x11\x44\x65registerRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"%\n\x12\x44\x65registerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9a\x02\n\x0eMonitorService\x12\x39\n\x08PingPong\x12\x14.monitor.PingRequest\x1a\x15.monitor.PongResponse\"\x00\x12\x41\n\nGetMetrics\x12\x17.monitor.MetricsRequest\x1a\x18.monitor.MetricsResponse\"\x00\x12\x41\n\x08Register\x12\x18.monitor.RegisterRequest\x1a\x19.monitor.RegisterResponse\"\x00\x12G\n\nDeregister\x12\x1a.monitor.DeregisterRequest\x1a\x1b.monitor.DeregisterResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGREQUEST._serialized_start=23
  _PINGREQUEST._serialized_end=53
  _PONGRESPONSE._serialized_start=55
  _PONGRESPONSE._serialized_end=86
  _METRICSREQUEST._serialized_start=88
  _METRICSREQUEST._serialized_end=125
  _METRICSRESPONSE._serialized_start=127
  _METRICSRESPONSE._serialized_end=158
  _REGISTERREQUEST._serialized_start=160
  _REGISTERREQUEST._serialized_end=198
  _REGISTERRESPONSE._serialized_start=200
  _REGISTERRESPONSE._serialized_end=235
  _DEREGISTERREQUEST._serialized_start=237
  _DEREGISTERREQUEST._serialized_end=277
  _DEREGISTERRESPONSE._serialized_start=279
  _DEREGISTERRESPONSE._serialized_end=316
  _MONITORSERVICE._serialized_start=319
  _MONITORSERVICE._serialized_end=601
# @@protoc_insertion_point(module_scope)
